### ISSUE TITLE
MVP Checklist

### ISSUE THREAD

**Issue by suesitran** [suesitran/interactive_diary#29]
# MVP Iteration
Start: 21 Aug 2022
End: 30 Nov 2022

# Features:
List of features to be included in MVP

 ### Online Anonymous
The basic function for Online Anonymous mode
- [x] Map #30 
- [x] Core UI: Map marker design #44 
- [x] Display marker on map
- [x] Display content bottom drawer
- [x] Offline Anonymous
- [x] Core UI: Date text field with error label #33 
- [x] Core UI: primary and secondary buttons #35 
- [x] Location permission #26 
- [x] Location service #12
- [x] Local storage😃  Hive #36
- [x] store diary content as text: time stamp in UTC, location lat/lng, Diary text content

 

Stretch goal: 
- [ ] onboarding 
- [ ] Cloud storage
- [ ] Login to switch between local storage and cloud storage
- [ ] Authentication😀  register with Google account #15 

### App Theme settings
Use theme Peaceful beach for light theme, and Fire at the Beach for dark theme

Peaceful beach - light theme
- background color: `#ffffff`
- primary color: Dodger Blue `#149DF1`
- onPrimary color: Blue Zodiac `#12375C`
- Secondary color: Jagged Ice `#C4E8E9`
- onSecondary color: East Bay `#40547B`

Fire at the beach - dark theme
- background color: `#262335`
- primary color: Casablanca `#F6C746`
- onPrimary color: Thunder `#2A212A`
- Secondary color: Mamba `#b8a7cf`
- onSecondary color: Cape Palliser `#6b230d`

#### Text theme
Use default material text theme setting: https://api.flutter.dev/flutter/material/TextTheme-class.html
